### ISSUE TITLE
Link plugin (anchor) decorators not working

### ISSUE THREAD

**Issue by igor-sysoev** [vacenz/megadraft-js-plugins#20]
Hi,

I'm using custom decorators with draft.js and now my links don't have any styles on them. Is there some way of setting them manually?
```
 const linkPlugin = createLinkPlugin({
      placeholder: "",
      theme: {
        link: {
          color: 'red'
        }
      }
    })

```
This doesn't work. In fact any option I try setting through there doesn't seem to appear.

**Comment by anatooly** [comment]
@supasus  How did you solve the problem?
